server:
  port: 8080

spring:
  application:
    name: document
    api:
      max-limit-results: 10

logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info

info:
  app:
    name: DocumentApi
    version: 1.0.0
    description: Index and search for documents
    maintainer: joaofonseca