cloud:
  aws:
    credentials:
      access-key: nonImportant
      secret-key: nonImportant
    region:
      static: eu-west-1
    sqs:
      endpoint: http://localhost:4566
    sns:
      endpoint: http://localhost:4566

logging:
  level:
    com.bvnk: DEBUG

management:
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/banking
    username: username
    password: password